---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: homarr-secrets
  namespace: homarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  suspend: false
  secretTemplates:
    - name: homarr-oidc-secret
      stringData:
        client-id: ENC[AES256_GCM,data:1uoQdfon,iv:1ZOfDJRakZ9V5AGjyWelHtv95yx5DQj1nsP42osX/mE=,tag:kmMGLRbbKRvHccrNT8x8uA==,type:str]
        client-secret: ENC[AES256_GCM,data:MUTyv3xxLQEbmMSP47fMxI3MNJzD55FJ4aOtCiMwrSY=,iv:OFY/hutgwZQ4zI9HSI3twKeAXnrjlP1fB5qSN+TdiSo=,tag:8ZVd+zwVEtP/ZL0DGsRmAQ==,type:str]
    - name: db-secret
      stringData:
        db-encryption-key: ENC[AES256_GCM,data:yq1ZyF68PAIImIn3yF5vcJQBoo6cpRxsiAgByuP34xeHlQpKLCw27yLGDcAShp+Ex7pcLIXzaXb4+H6Brjdx6A==,iv:aSCMOpJBLngaHTdC7lSwmEKzH+d5H6EiToXgpL8g+ZU=,tag:eLowjD8HwkUs+LMRyyQeFw==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcWthNlNBbUFSQ08wVkFG
        azV5WTMySVZEaUV6NWFjbUo1bGpMdlE2STNnCkROTW56N3h2S3JuUGRXZkNGUGVv
        UlJxaDMzK0RORGd3cXJHeUcyQncxbFEKLS0tIElobXpmcHZVNGhKL0Y0MDBDVXZ1
        YkhVUE5pMkl2Q2JJTEJSYVVQejRPNHcKb3MFFgyFKZ2u1tc4aPHiNOHmAQZexlo/
        KY3DWPs9oXVfov0jTxT+TRBvDTqCfPATVR5HjVW24MsffzzIQacSjw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1plz8979pv8n3thaq2vhz9a8rx8cdvwxkqu5u292t2uznrvld5q4qsy2vkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5em8rOVRJUEJGRk53aUI0
        SUZLVWptbjUwc0NheklMSSs1WGIvL1FUOURnCk5QblUvcFVtZFIrK1pmWnVSNkNU
        c2NtV3JGc1RYOStyWWtGVzZUMURGdkEKLS0tIGZYRUdDSmduSllyOStzOEQ3Y2d2
        aHNpU0RYbG5INGxqUEVscEM3NTd6cEEKJGLI511wzTCw+dqA2bcb3COZ0KkxwzBE
        u9hoFQj7Y4LbEX9sncmMNL4EIu5H9luViJvgsrK5hV+JC1+3HzMw+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-13T18:02:58Z"
  mac: ENC[AES256_GCM,data:+FC4BIYCc9+3oaQwFYuP6zR+qCiz5Ia7OVgYxGcKbx1DdId+8Xf8rb6oRWrPTzwlROpTGzcqBx5DuCrXA0AM+a8vzwUUNdDlyZbTxG0DC1B4XLAcwCER3rzAQ/fVpb65wTwfewBJJs4zJJD3468VUNSMk1X19jRZ1PXIO1gckiI=,iv:YbD2JFNdTmYuCi7ubfQarxv2KQ2OdjgPRA4s+Pl13pQ=,tag:y2fxomVNLW3jogsLO+kNBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
