---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  suspend: false
  secretTemplates:
    - name: nextcloud-redis
      stringData:
        password: ENC[AES256_GCM,data:PzM06bR2o/bBFnw685zc+NPrWHvCyN9YzY7XEdts2QoqYxbNAP0aMrqdbEMtsGIuqBqGuS+CmyQcQljFmDZqKA==,iv:4ZkbZCi/uDy/+WZAxKiWB3LdnVY/LMa1mnXgLf3jDGI=,tag:gv3KTIGjV5oKHuewwS1r7g==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaEROTWY2WjljekI3dzV1
        KzZMN09NenRMVWhKL0l0R2c4M0V2emRNTkJrCmw2dGt3dWhGRWg4OVpjR3FweXRs
        V2l4QmgvOXd2cjBXVi93TDFFRVlvaHcKLS0tIDZWNDk5NWpHZ2NPdTRpMVplNzE4
        eXRpWFpjdEVzeXhZc0ZsVmtDUjExUmMKRvWLdLcpTKOVmg21nikAVrPQ390LNtCf
        dL8AqgfAOMZRECiboL5syjGBE+tfddyzIEkP39pKaT6OKWUQMKICdw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1plz8979pv8n3thaq2vhz9a8rx8cdvwxkqu5u292t2uznrvld5q4qsy2vkd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESEd1ZjNkcmdScFFjOHRw
        d2pwNkVIWnhkYnpvODd5RjVYZ2kxZDNNMzFJClBybG9lWENzZ2hxMWpzVi84dEN2
        dHVBN0NqQjcrbFN1NE9xYWNCdHEvWm8KLS0tIENDUmRqT3JRUFpYaXgyWE9FbFhY
        S1diNFRuamVveWJ1aUpJaUUzQ3I4OTAKA7atqVerh4WYUzWZGAskJ25EUjuxIipx
        ic+nwf60/aVxkpKtmjXndowlES3/SKEDiGn4RyI4bihYfekdGzbO1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-08T07:33:39Z"
  mac: ENC[AES256_GCM,data:Pa/OwfEr8GMPHwYtH8Ng77TiaKl34GhbDn2yzds7jcbsdHnoL81i3dSa9XptGrANQc0murIWyrI7NYRASAgzpOoYq+PAbF6JjeK8p0DIORVfrH9iQfoQDvgKTlxl/9DBW8lYFdOycNm/uiB1nfhXdRPdcTBzOccIZpdlB+nQmZw=,iv:2GeWyQhIYAVm7guvPCqmSGNe31wljM7Xs2c3RnVzBY8=,tag:7cho3dnao0r8uxV3/tzxJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
