---
nextcloud:
  host: nextcloud.maddin.dev
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
  configs:
    custom.config.php: |
      <?php
      $CONFIG = array (
        'skeletondirectory' => '',
        'hide_login_form' => true,
      );

cronjob:
  enabled: true

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-db-rw:5432
  existingSecret:
    enabled: true
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password
    databaseKey: dbname

persistence:
  enabled: true
  storageClass: synology
  size: 500Gi
