---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  labels:
    app-type: homelab
spec:
  project: default
  sources:
    - repoURL: https://homarr-labs.github.io/charts/
      chart: homarr
      targetRevision: 5.5.0
      helm:
        valueFiles:
          - $app/apps/homarr/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_apps.git
      targetRevision: HEAD
      ref: app
      path: apps/homarr
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
