---
nextcloud:
  host: nextcloud.maddin.dev
  configs:
    custom.config.php: |
      <?php
      $CONFIG = array (
        'skeletondirectory' => '',
        'hide_login_form' => true,
        'maintenance_window_start' => 2,
        'files.chunked_upload.max_size' => 99000000,
      );

cronjob:
  enabled: true

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-db-rw:5432
  existingSecret:
    enabled: true
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password
    databaseKey: dbname

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: nextcloud-redis
    existingSecretPasswordKey: password
  global:
    storageClass: ceph-block

persistence:
  enabled: true
  storageClass: ceph-block
  size: 16Gi
  nextcloudData:
    enabled: true
    storageClass: synology
    size: 1000Gi
